# min height d 0; max height d 1
#            angle_min d -1.57  angle_max d 1.57 angle_increment 0.0087
#            scan_time 1/30  
#            range_min 0.45 range_max 4.0
        
min_height: 0.0 
max_height: 2.0
angle_min: -3.14
angle_max: 3.14
angle_increment: 0.0087
scan_time: 0.3333
range_min: 0.7
range_max: 40.0
target_frame: top_chassis_link
transform_tolerance: 0.01
use_inf: true
concurrency_level: 1   